language: node_js
node_js:
  - 10
script: echo "Running tests against $(node -v)..."
script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage